require "sig_shorthand/version"

module SigShorthand
  class Error < StandardError; end

  # grammar:
  # ABBREV ABBREV ABBREV
  # ' ' = whitespace
  # ABBREV = Q\d | Q\d-\d | Q\dM | QAFTER | Q | QD | ...


  # Order is important. Regexp will take the first thing that matches
  # so 1C vs 1CAM, if 1C|1CAM then 1CAM will match to 1C + AM
  # while 1CAM|1C will match to 1CAM which is what we actually want.
  DEFINITIONS = [
      ["\\.25L", "TAKE 1/4 TEASPOONFUL"],
      ["\\.25T", "TAKE 1/4 TABLET"],
      ["\\.5-1T", "TAKE 1/2 TO 1 TABLET"],
      ["\\.5H", "1/2 HOUR"],
      ["\\.5L", "GIVE 1/2 TEASPOONFUL"],
      ["\\.5ML", "GIVE 0.5ML "],
      ["1-2C", "TAKE 1 OR 2 CAPSULES"],
      ["1-2G", "TAKE 1 TO 2 DROPS"],
      ["1-2I", "USE 1 TO 2 INHALATIONS"],
      ["1-2P", "TAKE 1 TO 2 PUFFS"],
      ["1-2T", "TAKE 1 TO 2 TABLETS"],
      ["1\\.5H", "1 AND 1/2 HOURS"],
      ["1/2SUP", "INSERT 1/2 SUPPOSITORY"],
      ["1CAM", "TAKE 1 CAPSULE EACH MORNING"],
      ["1C", "TAKE 1 CAPSULE"],
      ["1G", "USE 1 DROP"],
      ["1H", "1 HOUR"],
      ["1I", "USE 1 INHALATION"],
      ["1L", "TAKE 1 TEASPOONFUL"],
      ["1ML", "1ML"],
      ["1P", "TAKE 1 PUFF"],
      ["1PR", "INSERT 1 SUPPOSITORY RECTALLY"],
      ["1S", "USE 1 SPRAY"],
      ["1T", "TAKE 1 TABLET"],
      ["2C", "TAKE 2 CAPSULES"],
      ["2C", "TAKE 2 CAPSULES"],
      ["2G", "USE 2 DROPS"],
      ["2I", "USE 2 INHALATIONS"],
      ["2L", "TAKE 2 TEASPOONSFUL"],
      ["2P", "TAKE 2 PUFFS"],
      ["2S", "USE 2 SPRAYS"],
      ["2T", "TAKE 2 TABLETS"],
      ["3\\/4L", "TAKE 3/4 TEASPOONFUL"],
      ["3C", "TAKE 3 CAPSULES"],
      ["3L", "TAKE 3 TEASPOONFUL"],
      ["3T", "TAKE 3 TABLETS"],
      ["5G", "5 DROPS"],
      ["5ML", "GIVE 5ML"],
      ["AAA", "APPLY TO AFFECTED AREA"],
      ["AB", "AFTER BREAKFAST"],
      ["AD", "IN THE RIGHT EAR"],
      ["AEY", "AFFECTED EYE(S)"],
      ["AIE", "TO ALTERNATING INNER EAR FLAP"],
      ["AM", "IN THE MORNING"],
      ["ANX", "ANXIETY"],
      ["APBID", "APPLY TWICE A DAY"],
      ["APP", "APPLICATOR"],
      ["APQID", "APPLY FOUR TIMES A DAY"],
      ["APTID", "APPLY THREE TIMES A DAY"],
      ["AP", "APPLY"],
      ["ASE", "IN THE LEFT EAR"],
      ["AS,", "IN THE LEFT EAR"],
      ["ATF", "APPLY TO FACE"],
      ["ATH", "APPLY TO HANDS"],
      ["ATS", "APPLY TO SKIN"],
      ["AUD", "APPLY AS DIRECTED"],
      ["AU", "IN BOTH EARS"],
      ["BA", "BACKACHE"],
      ["BB", "BEFORE BEDTIME"],
      ["BID", "TWICE DAILY"],
      ["BM", "BOWEL MOVEMENT"],
      ["C1T", "CHEW 1 TABLET"],
      ["C2T", "CHEW 2 TABLETS"],
      ["CAPS", "CAPSULES"],
      ["CAP", "CAPSULE"],
      ["CHS", "CHEWABLES"],
      ["CH", "CHEWABLE"],
      ["CMPD", "**COMPOUNDED BY PHYSICIAN'S REQUEST**"],
      ["CTS", "CHEW TREATS"],
      ["CT", "CHEW TREAT"],
      ["DISCOL", "*MAY DISCOLOR URINE OR STOOL*"],
      ["DNC", "*DO NOT CHEW*"],
      ["DND", "*DO NOT DRIVE*"],
      ["DNR", "*DO NOT REFRIGERATE*"],
      ["DR", "DOCTOR"],
      ["DU", "DUCIBITUS ULCER"],
      ["DYSM", "DYSMENNORHEA"],
      ["EOD", "EVERY OTHER DAY"],
      ["EXT", "*FOR EXTERNAL USE ONLY*"],
      ["FS", "FOLLOWING SOAKS"],
      ["G1", "GIVE 1"],
      ["G2", "GIVE 2"],
      ["G", "GIVE"],
      ["GTTS", "DROPS"],
      ["GTT", "DROP"],
      ["GT", "DROP"],
      ["IBD", "INFLAMMATORY BOWEL DISEASE"],
      ["INJ", "INJECT"],
      ["INS", "INSTILL"],
      ["KR", "*KEEP IN REFRIGERATOR*"],
      ["LOZ", "LOZENGE"],
      ["MDC", "*MAY CAUSE DROWSINESS*"],
      ["MDD", "MAXIMUM DAILY DOSE OF"],
      ["NA", "*NO ALCOHOL*"],
      ["NAU", "NAUSEA"],
      # ["NH", "*LOT # ______________    EXP. __________"],
      ["NOASP", "*DO NOT TAKE WITH ASPIRIN*"],
      ["NOMILK", "*AVOID DAIRY PRODUCTS WITHIN 2 HOURS*"],
      ["NOSWAL", "DO NOT SWALLOW"],
      ["NTF", "*TAKE ON AN EMPTY STOMACH*"],
      ["NWFE", "*DON'T TAKE WITH IRON PRODUCTS*"],
      ["OC", "OF CYCLE"],
      ["OD", "TO THE RIGHT EYE"],
      ["OS", "IN THE LEFT EYE"],
      ["OU", "IN EACH EYE"],
      ["PC", "AFTER MEALS"],
      ["PM", "IN THE EVENING"],
      ["PO", "BY MOUTH"],
      ["PPI", "AS NEEDED FOR PAIN & INFLAMMATION"],
      ["PP", "AS NEEDED FOR PAIN"],
      ["PRC", "AS NEEDED FOR COUGH"],
      ["PREG", "*DO NOT TAKE IF PREGNANT*"],
      ["PRNAL", "AS NEEDED FOR ALLERGIES"],
      ["PRNANX", "AS NEEDED FOR ANXIETY"],
      ["PRNART", "AS NEEDED FOR ARTHRITIS"],
      ["PRNBA", "AS NEEDED FOR BACKACHE"],
      ["PRNBUR", "AS NEEDED FOR BURNING"],
      ["PRNCON", "AS NEEDED FOR CONGESTION"],
      ["PRNCOU", "AS NEEDED FOR COUGH"],
      ["PRNDE", "AS NEEDED FOR DEPRESSION"],
      ["PRNDI", "AS NEEDED FOR DIZZINESS"],
      ["PRNED", "AS NEEDED FOR EDEMA"],
      ["PRNHA", "AS NEEDED FOR HEADACHE"],
      ["PRNIF", "AS NEEDED FOR INFECTION"],
      ["PRNIT", "AS NEEDED FOR ITCHING"],
      ["PRNLC", "AS NEEDED FOR LEG CRAMPS"],
      ["PRNMC", "AS NEEDED FOR MENSTRUAL CRAMPS"],
      ["PRNMIG", "AS NEEDED FOR MIGRAINE HEADACHE"],
      ["PRNMR", "AS NEEDED FOR MUSCLE RELAXATION"],
      ["PRNN", "AS NEEDED FOR NAUSEA"],
      ["PRNP", "AS NEEDED FOR PAIN"],
      ["PRNSP", "AS NEEDED FOR SPASMS"],
      ["PRNSW", "AS NEEDED FOR SWELLING"],
      ["PRNWH", "AS NEEDED FOR WHEEZING"],
      ["PRN", "AS NEEDED"],
      ["Q12-24", "EVERY 12 TO 24 HOURS"],
      ["Q12", "EVERY 12 HOURS"],
      ["Q1M", "EVERY MONTH"],
      ["Q24", "EVERY 24 HOURS"],
      ["Q2", "EVERY 2 HOURS"],
      ["Q3-6", "EVERY 3 TO 6 HOURS"],
      ["Q3MIN", "EVERY 3 MINUTES"],
      ["Q3M", "ONCE EVERY 3 MONTHS"],
      ["Q3", "EVERY 3 HOURS"],
      ["Q48", "EVERY 48 HOURS"],
      ["Q4T6", "EVERY 4 TO 6 HOURS"],
      ["Q4", "EVERY 4 HOURS"],
      ["Q6-12", "EVERY 6 TO 12 HOURS"],
      ["Q6-8", "EVERY 6 TO 8 HOURS"],
      ["Q6", "EVERY 6 HOURS"],
      ["Q72", "EVERY 72 HOURS"],
      ["Q8-12", "EVERY 8 TO 12 HOURS"],
      ["Q8", "EVERY 8 HOURS"],
      ["QAFTER", "EACH AFTERNOON"],
      ["QD", "ONCE DAILY"],
      ["QHS", "EVERY NIGHT AT BEDTIME"],
      ["QID", "FOUR TIMES A DAY"],
      ["QM", "ONCE MONTHLY"],
      ["QOD", "EVERY OTHER DAY"],
      ["QOHS", "EVERY OTHER EVENING AT BEDTIME"],
      ["QO", "EVERY OTHER"],
      ["QW", "EACH WEEK"],
      ["Q", "EVERY"],
      ["SID", "ONCE DAILY"],
      ["SQ", "SUBCUTANEOUSLY"],
      ["SWR", "*SHAKE WELL AND REFRIGERATE*"],
      ["SW", "*SHAKE WELL*"],
      ["TABS", "TABLETS"],
      ["TAB", "TABLET"],
      ["TID", "THREE TIMES DAILY"],
      ["TO", "AIE ALTERNATING INNER EAR FLAP"],
      ["TSPS", "TEASPOONSFUL"],
      ["TSP", "TEASPOONFUL"],
      ["UAD", "USE AS DIRECTED"],
      ["UD", "AS DIRECTED"],
      ["UF", "UNTIL FINISHED"],
      ["UOD", "UNTIL OTHERWISE DIRECTED"],
      ["VET", "VETERINARIAN"],
      ["WF", "WITH FOOD"],
      ["WGW", "*TAKE WITH A GLASS OF WATER*"],
      ["X10", "FOR 10 DAYS"],
      ["X14", "FOR 14 DAYS"],
      ["X24", "FOR 24 DAYS"],
      ["X21", "FOR 21 DAYS"],
      ["X2", "FOR 2 DAYS"],
      ["X30S", "FOR 30 SECONDS"],
      ["X30", "FOR 30 DAYS"],
      ["X3", "FOR 3 DAYS"],
      ["X4", "FOR 4 DAYS"],
      ["X5", "FOR 5 DAYS"],
      ["X6", "FOR 6 DAYS"],
      ["X7", "FOR 7 DAYS"],
      ["\\&", "AND"],
      ["\\|", "OR"],
  ]

  REGEX = Regexp.new(DEFINITIONS.map(&:first).map{|w| "(#{w})"}.join("|") + '|(\\w)', Regexp::IGNORECASE)

  class Vet
    def self.translate(str)
      result = []
      str.scan(REGEX) do |match|
        # ignore whitespace
        match_index = match.index { |v| !v.nil? }
        result << DEFINITIONS[match_index].last unless match_index === DEFINITIONS.size
      end
      result.join(' ')
    end
  end
end
